name: Testes em C

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Instalar build-essential
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compilar
      run: gcc -Isrc $(find src -name "*.c" ! -name "main.c") tests/*.c -o bin/tests/tests_exec

    - name: Rodar testes
      run: ./bin/tests/tests_exec
